# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotenks < Formula
  desc "CLI tool to generate Go type definitions from kintone TypeScript .d.ts files"
  homepage "https://github.com/goqoo-on-kintone/gotenks"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.0/gotenks_0.3.0_darwin_amd64.tar.gz"
      sha256 "eaf15839eb2645933dd0eb57a0412fc483abea6b10c30d1f80e8a99fe3b3d551"

      def install
        bin.install "gotenks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.0/gotenks_0.3.0_darwin_arm64.tar.gz"
      sha256 "8e9102ffdbf798ce1b4ddac2cfca5fe36de0a88ea104955ec84778ca6362df5f"

      def install
        bin.install "gotenks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.0/gotenks_0.3.0_linux_amd64.tar.gz"
      sha256 "ced89d9e464a9651fbb3b887a54d73513e608f33b7a6206cc37c7c1049fe5a59"
      def install
        bin.install "gotenks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.0/gotenks_0.3.0_linux_arm64.tar.gz"
      sha256 "1c60e31af8420eeecbe2c3bd1596befbbb5eab01a35da77508011cf087120c14"
      def install
        bin.install "gotenks"
      end
    end
  end

  test do
    system "#{bin}/gotenks", "-h"
  end
end
