# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotenks < Formula
  desc "CLI tool to generate Go type definitions from kintone TypeScript .d.ts files"
  homepage "https://github.com/goqoo-on-kintone/gotenks"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.2/gotenks_0.3.2_darwin_amd64.tar.gz"
      sha256 "4bc7e0b8afcb4652b6c19acfcfca9245b76dbc571b383f7a5bbd5b081e6d8fa0"

      def install
        bin.install "gotenks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.2/gotenks_0.3.2_darwin_arm64.tar.gz"
      sha256 "13765ebc293f4db3ad28f2209cead5d023d69b0b135b3820245c905b949cb684"

      def install
        bin.install "gotenks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.2/gotenks_0.3.2_linux_amd64.tar.gz"
      sha256 "132f0fb913d049a41a9f32eb5e8f3fcab110e04b9b5c9f66081431777d3fd18c"
      def install
        bin.install "gotenks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.2/gotenks_0.3.2_linux_arm64.tar.gz"
      sha256 "1243ba21e8d4d29603001844bfe9820ef5a6abf9f898ccc767a8bea2e1050964"
      def install
        bin.install "gotenks"
      end
    end
  end

  test do
    system "#{bin}/gotenks", "-h"
  end
end
