# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotenks < Formula
  desc "CLI tool to generate Go type definitions from kintone TypeScript .d.ts files"
  homepage "https://github.com/goqoo-on-kintone/gotenks"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.1/gotenks_0.3.1_darwin_amd64.tar.gz"
      sha256 "0cc34554e31169463579889aa65952eb20601f1cdde784f6aef983c557e9a0de"

      def install
        bin.install "gotenks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.1/gotenks_0.3.1_darwin_arm64.tar.gz"
      sha256 "778cdb7a48eb861090cbd935d57c7eae1e2092d7ab2d748425882c3da18c7282"

      def install
        bin.install "gotenks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.1/gotenks_0.3.1_linux_amd64.tar.gz"
      sha256 "afe76a696e75eba5af9e8cedab1241ef9817472d8388b5f14334e418314ed942"
      def install
        bin.install "gotenks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goqoo-on-kintone/gotenks/releases/download/v0.3.1/gotenks_0.3.1_linux_arm64.tar.gz"
      sha256 "7c568ce0b4750bc08a99262e7733a4e46352549681650e4ec89371ff70d949ea"
      def install
        bin.install "gotenks"
      end
    end
  end

  test do
    system "#{bin}/gotenks", "-h"
  end
end
